apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  labels:
    app: demo-voting-app
    name: voting-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
  selector:
    app: demo-voting-app
    name: voting-app-pod